# 긍정부정중립으로 나누기
str(tenet_moive)
tenet_moive$point = as.numeric(tenet_moive$point)
str(tenet_moive)
table(tenet_moive$point)

tenet_moive <- tenet_moive %>%
  mutate(feeling = ifelse(point >= 7, '긍정', ifelse(point >= 5, '중립', '부정'))) 
table(tenet_moive$feeling)
View(tenet_moive)

tenet_moive <- tenet_moive[c(1,3,2)]
tail(tenet_moive)
str(tenet_moive)

# 특수문자 제거
str_extract_all(tenet_moive$comment, '[[:punct:]]')     # 특수문자만 추출
tenet_moive_clean <- str_replace_all(tenet_moive$comment, '[[:punct:]]',' ')


# 품사태깅(명사만 이용)
word_tenet <- NULL
for(i in 1:length(tenet_moive_clean)){
  pos_tenet_movie <- SimplePos09(tenet_moive_clean[i])
  vector_tenet <- as.vector(na.omit(str_match(unlist(pos_tenet_movie), '([가-힣]+)/N')[,2]))
  vector_tenet_2 <- Filter(function(x){nchar(x) >= 2}, vector_tenet)
  paste_movie <- paste(vector_tenet_2, collapse = ' ')
  word_tenet[i] <- paste_movie
}
word_tenet
length(word_tenet)

# corpus 변환
corp_tenet <- VCorpus(VectorSource(word_tenet))
inspect(corp_tenet)          
corp_tenet[[1]]$content

# corpus 단어 정제
# 많은 양의 오타와 비슷한 단어를 하나로 바꾸는 과정을 실시(분석의 정확성을 높이고 시간이 가장 많이 소요됨)
str_extract_all(corp_tenet, '스포일러[[:alpha:]]{0,}|스포[[:alpha:]]{0,}')
View(sort(table(str_extract_all(corp_tenet_2, '이해[[:alpha:]]{0,}')[[1]]), decreasing = T))
str_extract_all(corp_tenet, '이해안[[:alpha:]]{0,}|이해불[[:alpha:]]{0,}|이해못[[:alpha:]]{0,}|이해를[[:alpha:]]{1,}|
                이해가안되서|이해하고[[:alpha:]]{1,}|이해하기[[:alpha:]]{1,}|이해가안|이해는가야지|
                이해자제|이해가것냐|이해하겠|이해하는건|이해도안[[:alpha:]]{0,}')[[1]]
str_extract_all(corp_tenet, '이해력[[:alpha:]]{0,}|이해해[[:alpha:]]{0,}|이해했[[:alpha:]]{0,}|
                이해가가|이해가고|이해가되더라구요|이해됨|이해함|이해가능|
                이해됐[[:alpha:]]{0,}|이해됬[[:alpha:]]{0,}|이해감|이해다[[:alpha:]]{0,}|
                이해가됩[[:alpha:]]{0,}|이해가쉽[[:alpha:]]{0,}|이해가되[[:alpha:]]{0,}')[[1]]
View(sort(table(str_extract_all(corp_tenet_2, '이해[[:alpha:]]{0,}')[[1]]), decreasing = T))
View(sort(table(str_extract_all(corp_tenet_2, '이해[[:alpha:]]{0,}')[[1]]), decreasing = T))
str_extract_all(corp_tenet_2, '크리스토퍼[[:alpha:]]{0,}|놀란[[:alpha:]]{0,}|김독[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '다크나이트[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '인셉션[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '인터스텔라[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '덩케르크[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '메멘토[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '액션[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '어렵[[:alpha:]]{0,}|어려[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '인비[[:alpha:]]{0,}|인버[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '난해[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '모르[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '영화보[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '재밌[[:alpha:]]{0,}|재미[[:alpha:]]{0,}|재밋[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '복잡[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '불친절[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '테넷[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}영화[[:alpha:]]{0,}')
View(table(str_extract_all(corp_tenet_2, '[[:alpha:]]{0,}')[[1]]))
str_extract_all(corp_tenet, '가능[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '가득[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}감독[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '감상[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '감정[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}강추[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '감동[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}꿀잼[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}노잼[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}개봉[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '개소[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}재미[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}재밌[[:alpha:]]{0,}|[[:alpha:]]{0,}재밋[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}재미없[[:alpha:]]{0,}|[[:alpha:]]{0,}재미가없[[:alpha:]]{0,}|[[:alpha:]]{0,}재미드럽게없[[:alpha:]]{0,}|[[:alpha:]]{0,}재밌진않[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '계속[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '관객[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}관객')
str_extract_all(corp_tenet, '관객[[:alpha:]]{0,}|[[:alpha:]]{0,}관객')
str_extract_all(corp_tenet, '관람[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '굿')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}굿[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '궁금[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '긴장[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}긴장[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '단순[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '당최|당췌|도대체')
str_extract_all(corp_tenet, '대단[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '대중[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '독창[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '떡밥[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '디테일[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}디테일')
str_extract_all(corp_tenet, '러닝[[:alpha:]]{0,}|상영시간')
str_extract_all(corp_tenet, '로버트[[:alpha:]]{0,}|[[:alpha:]]{0,}패틴슨')
str_extract_all(corp_tenet, '망작[[:alpha:]]{0,}|개망작')
str_extract_all(corp_tenet, '머리아[[:alpha:]]{0,}|머리쓰[[:alpha:]]{0,}|머리만[[:alpha:]]{0,}| 머리깨[[:alpha:]]{0,}|머리가[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '머릿[[:alpha:]]{0,}|머리[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '메세지[[:alpha:]]{0,}|메시지[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '명작[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}명작[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '몰입[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '물리[[:alpha:]]{0,}|[[:alpha:]]{0,}물리')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}물리[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '뭔내용[[:alpha:]]{0,}|뭔말[[:alpha:]]{0,}|뭔소리[[:alpha:]]{0,}|뭔진[[:alpha:]]{0,}|뭔진[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '뭔말[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '뭔소리[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '뭔진[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '뭐지[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '뭘본[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '미래[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '방법[[:alpha:]]{0,}|방식[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '배경[[:alpha:]]{0,}|사운드[[:alpha:]]{0,}|소리[[:alpha:]]{0,}|음악[[:alpha:]]{0,}|음향[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '사운드[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '소리[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '음악[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '음향[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '남주[[:alpha:]]{0,}|여주[[:alpha:]]{0,}|[[:alpha:]]{0,}배우[[:alpha:]]{0,}|등장[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}배우[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '등장[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '번역[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '보기[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '부족[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '비교[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '생각[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '설명[[:alpha:]]{1,}')
str_extract_all(corp_tenet, '설정[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '소름[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '속도[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '솔직[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '순방[[:alpha:]]{0,}|역방[[:alpha:]]{0,}|순행[[:alpha:]]{0,}|역행[[:alpha:]]{0,}|시간역[[:alpha:]]{0,}|역재생[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '역방[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '역행[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '순행[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '시간역[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '역재생[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '스토리[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '시각[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '시간여행[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '시작[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '신기[[:alpha:]]{0,}|신박[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '신선[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '실패[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '전투[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '아쉬[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '악당[[:alpha:]]{0,}|악역[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '압도[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '역대[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}감독')
str_extract_all(corp_tenet, '연기[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '영상[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '예정[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '오랜만[[:alpha:]]{0,}|오래간만[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '완벽[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '욕구[[:alpha:]]{0,}|욕심[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '용산[[:alpha:]]{0,}|용아맥[[:alpha:]]{0,}|아이맥스[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '웅장[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '유튜브[[:alpha:]]{0,}|유튭[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '의도[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '이딴[[:alpha:]]{0,}|이따구[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '이론[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '이번[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '이상[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '인간[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '인물[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '일어난[[:alpha:]]{0,}|일어날[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '작품[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}모르겠[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '장면[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '재미[[:alpha:]]{0,}|재밌[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '전반[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '정신[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '임팩트[[:alpha:]]{0,}|절정[[:alpha:]]{0,}|정점[[:alpha:]]{0,}|하이라이트[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '존나[[:alpha:]]{0,}|매우[[:alpha:]]{0,}|정말[[:alpha:]]{0,}|진심[[:alpha:]]{0,}|진정[[:alpha:]]{0,}|진짜[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '좋[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '지루[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '집중[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '집중도않[[:alpha:]]{0,}|집중이안[[:alpha:]]{0,}|집중력장애|집중안')
str_extract_all(corp_tenet, '짜여[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '짜임[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '천재[[:alpha:]]{0,}|[[:alpha:]]{0,}천재')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}천재')
str_extract_all(corp_tenet, '초반[[:alpha:]]{0,}|첫장[[:alpha:]]{0,}|앞부분[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '첫장[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '앞부분[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '시작[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '촬영[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '최강[[:alpha:]]{0,}|최고[[:alpha:]]{0,}|최대[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '최고[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '최대[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '최소[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '추천[[:alpha:]]{0,}|[[:alpha:]]{0,}추천')
str_extract_all(corp_tenet, '[[:alpha:]]{0,}추천')
str_extract_all(corp_tenet, '충격[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '피곤[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '하나도[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '일도[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '해석[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '후반[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '흥미[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '훌륭[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '힘들[[:alpha:]]{0,}|힘듦[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '힘듦[[:alpha:]]{0,}')
str_extract_all(corp_tenet, '웅장[[:alpha:]]{0,}')


corp_tenet_2 <- tm_map(corp_tenet, content_transformer(function(x) gsub('스포일러[[:alpha:]]{0,}|스포[[:alpha:]]{0,}', '스포일러', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해안[[:alpha:]]{0,}|이해불[[:alpha:]]{0,}|이해못[[:alpha:]]{0,}|이해를[[:alpha:]]{1,}', '이ㄱ해불가', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해가안되서|이해하고[[:alpha:]]{1,}|이해하기[[:alpha:]]{1,}|이해가안|이해는가야지|이해가잘안', '이ㄱ해불가', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해자제|이해가것냐|이해하겠|이해하것냐|이해절대|이해하는건|이해도안[[:alpha:]]{0,}', '이ㄱ해불가', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해된적이없네용|이해하지마라|이해할수없는영화|이해할필요도없고', '이ㄱ해불가', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해력[[:alpha:]]{0,}|이해해[[:alpha:]]{0,}|이해했[[:alpha:]]{0,}|이해는했[[:alpha:]]{0,}', '이ㄱ해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해가가|이해가고|이해가되더라구요|이해됨|이해함|이해가능', '이ㄱ해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해됐[[:alpha:]]{0,}|이해됬[[:alpha:]]{0,}|이해감|이해다[[:alpha:]]{0,}', '이ㄱ해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해가됩[[:alpha:]]{0,}|이해가쉽[[:alpha:]]{0,}|이해가되[[:alpha:]]{0,}', '이ㄱ해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해하면|이해가풀리면서|이해도되긴하는데|이해도되긴하는데|이해도되긴하는데', '이ㄱ해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해[[:alpha:]]{0,}', '이해', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이ㄱ해감', '이해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이ㄱ해불가', '이해불가', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해감[[:alpha:]]{0,}', '이해감', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이해불가[[:alpha:]]{0,}', '이해불가', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('크리스토퍼[[:alpha:]]{0,}|놀란[[:alpha:]]{0,}|김독[[:alpha:]]{0,}', '놀란감독', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('다크나이트[[:alpha:]]{0,}', '다크나이트', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('인셉션[[:alpha:]]{0,}', '인셉션', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('인터스텔라[[:alpha:]]{0,}', '인터스텔라', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('덩케르크[[:alpha:]]{0,}', '덩케르크', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('메멘토[[:alpha:]]{0,}', '메멘토', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('액션[[:alpha:]]{0,}', '액션신', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('어렵[[:alpha:]]{0,}|어려[[:alpha:]]{0,}', '어려운', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('인비[[:alpha:]]{0,}|인버[[:alpha:]]{0,}', '인버전', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('난해[[:alpha:]]{0,}', '난해한', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('모르[[:alpha:]]{0,}', '모르겠다', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('영화보[[:alpha:]]{0,}', '영화보는', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('재밌[[:alpha:]]{0,}', '재미', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('복잡[[:alpha:]]{0,}', '복잡한', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('불친절[[:alpha:]]{0,}', '불친절', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('테넷[[:alpha:]]{0,}', '테넷', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}영화[[:alpha:]]{0,}', '영화', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('가능[[:alpha:]]{0,}', '가능', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('가득[[:alpha:]]{0,}', '가득', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}감독[[:alpha:]]{0,}', '놀란감독', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('감상[[:alpha:]]{0,}', '감상평', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('감정[[:alpha:]]{0,}', '감정', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}강추[[:alpha:]]{0,}', '강추', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('감동[[:alpha:]]{0,}', '감동', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}꿀잼[[:alpha:]]{0,}', '꿀잼', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}노잼[[:alpha:]]{0,}|개소[[:alpha:]]{0,}', '노잼', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}개봉[[:alpha:]]{0,}', '개봉', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}재미없[[:alpha:]]{0,}|[[:alpha:]]{0,}재미가없[[:alpha:]]{0,}|[[:alpha:]]{0,}재미드럽게없[[:alpha:]]{0,}|[[:alpha:]]{0,}재밌진않[[:alpha:]]{0,}', '재ㄱ미없음', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}재미[[:alpha:]]{0,}|[[:alpha:]]{0,}재밌[[:alpha:]]{0,}|[[:alpha:]]{0,}재밋[[:alpha:]]{0,}', '재미', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('재ㄱ미없음', '재미없음', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('계속[[:alpha:]]{0,}', '계속해서', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('관객가지고노는영화임걍|관객무시|관객우롱|관객이따라가긴|관객수준', '관ㄱ객우롱', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('관객[[:alpha:]]{0,}|[[:alpha:]]{0,}관객', '가능', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('관ㄱ객우롱', '관객우롱', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('관람[[:alpha:]]{0,}', '관람', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}굿[[:alpha:]]{0,}', '굿', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('궁금[[:alpha:]]{0,}', '궁금', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}긴장[[:alpha:]]{0,}', '긴장', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('단순[[:alpha:]]{0,}', '단순', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('당최|당쵀|도대체', '당최', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('대단[[:alpha:]]{0,}', '대단', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('대중[[:alpha:]]{0,}', '대중성', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('독창[[:alpha:]]{0,}', '독창성', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('독창', '독창성', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('떡밥[[:alpha:]]{0,}', '떡밥', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('디테일[[:alpha:]]{0,}', '디테일', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('러닝[[:alpha:]]{0,}|상영시간', '러닝타임', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('로버트[[:alpha:]]{0,}|[[:alpha:]]{0,}패틴슨', '로버트패틴슨', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('망작[[:alpha:]]{0,}|개망작', '망작', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('머리아[[:alpha:]]{0,}|머리쓰[[:alpha:]]{0,}|머리만[[:alpha:]]{0,}| 머리깨[[:alpha:]]{0,}|머리가[[:alpha:]]{0,}', '머ㄱ리', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('머릿[[:alpha:]]{0,}|머리[[:alpha:]]{0,}', '머리', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('머ㄱ리', '머리아픔', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('메세지[[:alpha:]]{0,}|메시지[[:alpha:]]{0,}', '메세지', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('명작까진', '평범', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}명작[[:alpha:]]{0,}', '명작', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('몰입[[:alpha:]]{0,}', '몰입', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}물리[[:alpha:]]{0,}', '물리', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('뭔내용[[:alpha:]]{0,}|뭔말[[:alpha:]]{0,}|뭔소리[[:alpha:]]{0,}|뭔진[[:alpha:]]{0,}|뭔진[[:alpha:]]{0,}', '뭔내용인지', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('뭘본[[:alpha:]]{0,}', '뭘본건지', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('방법[[:alpha:]]{0,}|방식[[:alpha:]]{0,}', '방법', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('배경[[:alpha:]]{0,}|사운드[[:alpha:]]{0,}|소리[[:alpha:]]{0,}|음악[[:alpha:]]{0,}|음향[[:alpha:]]{0,}', '음향', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('남주[[:alpha:]]{0,}|여주[[:alpha:]]{0,}|[[:alpha:]]{0,}배우[[:alpha:]]{0,}|등장[[:alpha:]]{0,}|인물[[:alpha:]]{0,}', '등장인물', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('번역[[:alpha:]]{0,}', '번역', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('부족[[:alpha:]]{0,}', '부족', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('비교[[:alpha:]]{0,}', '비교', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('생각[[:alpha:]]{0,}', '생각', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('설정[[:alpha:]]{0,}', '설정', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('소름[[:alpha:]]{0,}', '소름', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('속도[[:alpha:]]{0,}', '속도', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('솔직[[:alpha:]]{0,}', '솔직하게', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('순방[[:alpha:]]{0,}|역방[[:alpha:]]{0,}|순행[[:alpha:]]{0,}|역행[[:alpha:]]{0,}|시간역[[:alpha:]]{0,}|역재생[[:alpha:]]{0,}', '순행역행', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('스토리[[:alpha:]]{0,}', '스토리', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('시각[[:alpha:]]{0,}', '시각적', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('시간여행[[:alpha:]]{0,}', '시간여행', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('시작[[:alpha:]]{0,}', '시작부분', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('신기[[:alpha:]]{0,}|신박[[:alpha:]]{0,}', '신기한', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('신선[[:alpha:]]{0,}', '신선', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('실패[[:alpha:]]{0,}', '실패', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('전투[[:alpha:]]{0,}', '전투신', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('아쉬[[:alpha:]]{0,}', '아쉬움', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('악당[[:alpha:]]{0,}|악역[[:alpha:]]{0,}', '악역', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('압도[[:alpha:]]{0,}', '압도', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('역대[[:alpha:]]{0,}', '역대급', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}감독', '감독', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('연기[[:alpha:]]{0,}', '연기력', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('영상[[:alpha:]]{0,}', '영상미', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('예정[[:alpha:]]{0,}', '예정', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('오랜만[[:alpha:]]{0,}|오래간만[[:alpha:]]{0,}', '오랜만', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('완벽[[:alpha:]]{0,}', '완벽', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('욕구[[:alpha:]]{0,}|욕심[[:alpha:]]{0,}', '욕심', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('용산[[:alpha:]]{0,}|용아맥[[:alpha:]]{0,}|아이맥스[[:alpha:]]{0,}', '아이맥스', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('웅장[[:alpha:]]{0,}', '웅장', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('유튜브[[:alpha:]]{0,}|유튭[[:alpha:]]{0,}', '유튜브', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('의도[[:alpha:]]{0,}', '의도', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이딴[[:alpha:]]{0,}|이따구[[:alpha:]]{0,}', '이딴식으로', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이론[[:alpha:]]{0,}', '이론적', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이번[[:alpha:]]{0,}', '이번', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('이상[[:alpha:]]{0,}', '이상', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('인간[[:alpha:]]{0,}', '인간', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('일어난[[:alpha:]]{0,}|일어날[[:alpha:]]{0,}', '일어난', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('작품[[:alpha:]]{0,}', '작품', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('[[:alpha:]]{0,}모르겠[[:alpha:]]{0,}', '모르겠다', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('장면[[:alpha:]]{0,}', '장면', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('전반[[:alpha:]]{0,}', '전반적', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('정신[[:alpha:]]{0,}', '정신', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('임팩트[[:alpha:]]{0,}', '임팩트', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('절정[[:alpha:]]{0,}|정점[[:alpha:]]{0,}|하이라이트[[:alpha:]]{0,}', '하이라이트', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('존나[[:alpha:]]{0,}|매우[[:alpha:]]{0,}|정말[[:alpha:]]{0,}|진심[[:alpha:]]{0,}|진정[[:alpha:]]{0,}|진짜[[:alpha:]]{0,}', '정말', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('좋[[:alpha:]]{0,}', '좋음', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('집중도않[[:alpha:]]{0,}|집중이안[[:alpha:]]{0,}|집중력장애|집중안[[:alpha:]]{0,}', '집ㄱ중안됨', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('집중[[:alpha:]]{0,}', '집중', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('집ㄱ중안됨[[:alpha:]]{0,}', '집중안됨', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('짜여[[:alpha:]]{0,}|짜임[[:alpha:]]{0,}', '짜임새', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('창의[[:alpha:]]{0,}', '창의적', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('천재[[:alpha:]]{0,}|[[:alpha:]]{0,}천재', '천재', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('초반[[:alpha:]]{0,}|첫장[[:alpha:]]{0,}|앞부분[[:alpha:]]{0,}', '초반', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('촬영[[:alpha:]]{0,}', '촬영', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('최강[[:alpha:]]{0,}|최고[[:alpha:]]{0,}|최대[[:alpha:]]{0,}', '최고', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('최소[[:alpha:]]{0,}', '최소', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('추천[[:alpha:]]{0,}|[[:alpha:]]{0,}추천', '추천', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('충격[[:alpha:]]{0,}', '충격적', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('피곤[[:alpha:]]{0,}', '피곤', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('하나도[[:alpha:]]{0,}', '하ㄱ나도', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('하나[[:alpha:]]{0,}', '하나', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('하ㄱ나도[[:alpha:]]{0,}', '하나도', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('해석[[:alpha:]]{0,}', '해석', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('후반[[:alpha:]]{0,}', '후반부', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('흥미[[:alpha:]]{0,}', '흥미', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('훌륭[[:alpha:]]{0,}', '훌륭한', x)))
corp_tenet_2 <- tm_map(corp_tenet_2, content_transformer(function(x) gsub('힘들[[:alpha:]]{0,}|힘듦[[:alpha:]]{0,}', '힘듦', x)))



# 매트릭스 변환
tenet_dtm <- DocumentTermMatrix(corp_tenet_2, control = list(wordLengths = c(2, Inf)))
inspect(tenet_dtm)  # 단어 수: 7869
